### ISSUE TITLE
Invoke-RestMethod only shows 1000 entries

### ISSUE THREAD

**Issue by mrdominuzq** [Qumulo/PowerShellToolkit#1]
i have created get-qqdir

function Get-QQDir {
    <#
        .SYNOPSIS
            Get Directory
        .DESCRIPTION
            Retrieve Directory
        .PARAMETER Id [Directory or File ID]
            Directory or Directory ID
        .PARAMETER Path [Directory or FilePath]
            Directory
        .EXAMPLE
            Get-QQDir -Path [Directory Path] 
        #>
    
        [CmdletBinding()]
        param(
            [Parameter(Mandatory = $True,ParameterSetName = "Id")][ValidateNotNullOrEmpty()] [string]$Id,
            [Parameter(Mandatory = $True,ParameterSetName = "Path")][ValidateNotNullOrEmpty()] [string]$Path,
            [Parameter(Mandatory = $False)] [switch]$Json
        )
        if ($SkipCertificateCheck -eq 'true') {
            $PSDefaultParameterValues = @("Invoke-RestMethod:SkipCertificateCheck",$true)
        }
    
        try {
            # Existing BearerToken check
            if (!$global:Credentials) {
                Login-QQCluster
            }
            else {
                if (!$global:Credentials.BearerToken.StartsWith("session-v1")) {
                    Login-QQCluster
                }
            }
    
            $bearerToken = $global:Credentials.BearerToken
            $clusterName = $global:Credentials.ClusterName
            $portNumber = $global:Credentials.PortNumber
    
            $TokenHeader = @{
                Authorization = "Bearer $bearerToken"
            }
    
            if ($path) {
                $htmlPath = ([uri]::EscapeDataString($path))
                # API url definition
                $url = "/v1/files/$htmlPath/entries/?limit=10000"
            }
            elseif($id){
                $url = "/v1/files/$id/entries"
            }
        
                # API call run
                try {
                    $response = Invoke-RestMethod -SkipCertificateCheck -Method 'GET' -Uri "https://${clusterName}:$portNumber$url" -Headers $TokenHeader -ContentType "application/json" -TimeoutSec 60 -ErrorAction:Stop
    
                # Response
                if ($Json) {
                    return @($response) | ConvertTo-Json -Depth 10
                }
                else {
                    return $response
                }
            }
            catch {
                $_.Exception.Response
            }
        }
        catch {
            $_.Exception.Response
        }
    }
    

it only shows a 1000 entries, but if i do

$i =  Get-QQDir -Path "/Users" -Json | jq-win64.exe -r '.files[].path'

#Get-QQDir -Path /Users/Users1 -Json | jq-win64.exe -r '.files[].path' | out-file ./files.txt

$path = foreach ($p in $i) {
    Get-QQDir -Path $p -Json | jq-win64.exe -r '.files[].path'
}
    $path | out-file ./files.txt

i get 10.000 entries.

**Comment by BeratUlualan** [comment]
Hi,

We have a paging mechanism. You need to use the URL like below.

`/v1/files/2/entries/?after=4814&limit=2`

You can get that url like below from the previous API call result in a for loop.

 $url = $response.paging.next
