### ISSUE TITLE
Suggestion - NFS Management

### ISSUE THREAD

**Issue by ArieHein** [Qumulo/PowerShellToolkit#3]
At this time, there is only support for SMB management via the PowerShell module.
Can we get NFS management via the module as well ?

Im creating some automation around SMB and NFS and since i want to use PowerShell, I am not able to use same stack for both types of work.

TY

**Comment by BeratUlualan** [comment]
NFS functions are added with v6.2.1. Please check the latest version of PowerShell Toolkit
